name: Convert org to md

permissions:
  contents: write

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y pandoc
      - run: pandoc better-quarto.org -o README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate README.md from org file"
